# Generated by Django 6.0 on 2025-12-21 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_alter_customuser_email'),
        ('production', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.project'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='received_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_deliveries', to='core.employeeprofile'),
        ),
        migrations.AddField(
            model_name='productionbatch',
            name='inspected_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.employeeprofile'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.productionbatch'),
        ),
        migrations.AddField(
            model_name='brickstock',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.productionbatch'),
        ),
    ]
